import type { NextPage } from 'next'
import Head from 'next/head'
import Status from '../Components/Status';
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from './index.module.css';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashbord</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}> */}
      <main className={`${styles.homeDash} p-4`}>
        <Status/>
      </main>
    </div>
  )
}

export default Home
